# -*- coding: utf-8 -*-
"""ZomatoDataAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1YBfmU-w8yMAs50HremUKkcAtQkuH17
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/drive/MyDrive/Zomato data .csv')
df.head(10)

def handlerate(value):
  value=value.split('/')
  value=value[0]
  return float(value)

df['rate']=df['rate'].apply(handlerate)
df.head()

df.isnull().sum()

df.info()

df_maxvotes=df['votes'].max()
df_maxvotesname=df['name'][df['votes']==df_maxvotes]
df_maxvotesname

sns.barplot(x=df['listed_in(type)'],y=df['votes'],data=df)

sns.countplot(x=df['approx_cost(for two people)'])

sns.histplot(df['rate'],bins=6)
plt.title('rate distribution')
plt.show()

sns.countplot(x=df['online_order'])
plt.title('online order')
plt.show()

listed_df=df['listed_in(type)']
sns.countplot(x=listed_df)
plt.title('listed in')
plt.show()

df_group=df.groupby('listed_in(type)')['votes'].sum()
df_res=pd.DataFrame({'votes':df_group})
df_res.head()

plt.plot(df_res,marker='o',linestyle='--')
plt.xlabel('type')
plt.ylabel('votes')
plt.title('votes')
plt.show()

plt.figure(figsize=(8,8))
sns.boxplot(x='online_order',y='rate',data=df)
plt.show()

plt.figure(figsize=(8,8))
sns.boxplot(x='online_order',y='votes',data=df)
plt.show()

df_pivot = df.pivot_table(index='listed_in(type)', columns='online_order', aggfunc='size', fill_value=0)
sns.heatmap(df_pivot, annot=True, fmt='d')
plt.title("Heatmap")
plt.xlabel("Online Order")
plt.ylabel("Listed In (Type)")
plt.show()